# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJSUSRAC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SJSUSRAC
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod "Macaw", "0.9.5"

  target 'SJSUSRACTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJSUSRACUITests' do
    # Pods for testing
  end

end
